// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhvbYDFxS1E192P2L6ropXhN16ZpMlwc0',
    appId: '1:689901422797:web:ad052b1962431c71b0c184',
    messagingSenderId: '689901422797',
    projectId: 'workshop-df496',
    authDomain: 'workshop-df496.firebaseapp.com',
    storageBucket: 'workshop-df496.appspot.com',
    measurementId: 'G-LBXL3W0XE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC6-tSU_e26ZoiEFI8KAJmqcf49S8Toik',
    appId: '1:689901422797:android:aba600f410b35b0eb0c184',
    messagingSenderId: '689901422797',
    projectId: 'workshop-df496',
    storageBucket: 'workshop-df496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBwLtsIAfVkU3PysPo1kNpmHUb08qhFEc',
    appId: '1:689901422797:ios:0e5237af3f54bc92b0c184',
    messagingSenderId: '689901422797',
    projectId: 'workshop-df496',
    storageBucket: 'workshop-df496.appspot.com',
    iosClientId: '689901422797-7ee5kuehlklqlh3ullikqrv4kcopc1oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.workshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBwLtsIAfVkU3PysPo1kNpmHUb08qhFEc',
    appId: '1:689901422797:ios:74ec1da0311badaeb0c184',
    messagingSenderId: '689901422797',
    projectId: 'workshop-df496',
    storageBucket: 'workshop-df496.appspot.com',
    iosClientId: '689901422797-p4ogk2p2thoserrd06hlnqm746geh650.apps.googleusercontent.com',
    iosBundleId: 'com.example.workshop.RunnerTests',
  );
}
